name: DevOps Demo
on:
  push:
  workflow_dispatch:
jobs:
  information:
    runs-on: ubuntu-latest
    steps:
      - name: Show Repository
        env:
          REPO: ${{ github.repository }}
        run: |
          echo "Repository: $REPO"
      - name: Show Branch
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          echo "Branch: $BRANCH"
      - name: Show User
        env:
          USER: ${{github.actor}}
        run: |
          echo "User: $USER"
  second-job:
    needs: information
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Second Job
        run: echo "This is another job."
  third-job:
    needs: second-job
    runs-on: ubuntu-latest
    steps:
      - name: Third Job
        run: echo "This is the third job."
